### ISSUE TITLE
Añadir petition como ciudadano no funciona y como governmentAgent no me permite el acceso

### ISSUE THREAD

**Issue by ruano23** [MarioBG/AcmeHisperia#11]

**Comment by ruano23** [comment]
Como bank Agent tampoco me permite el acceso a esa url.

**Comment by Juaniito92** [comment]
@ruano23 a que te refieres con añadir petition como ciudadano? a crearla? solamente los ciudadanos pueden crear peticiones. A que url no te permite el acceso?

**Comment by ruano23** [comment]
@Juaniito92 Carlos Ruano:
http://localhost:8080/Acme-Citizen/petition/citizen/addGovernmentAgent.do?petitionId=&governmentAgentId=150

**Comment by Juaniito92** [comment]
@ruano23 te falta especificar el petitionId
