### ISSUE TITLE
List petitions

### ISSUE THREAD

**Issue by ruano23** [MarioBG/AcmeHisperia#14]
La lista de peticiones de un cierto ciudadano no se pueden visualizar.
petitions / list.do ? citizenId=155

**Comment by Juaniito92** [comment]
He accedido a la url petition/list.do?citizenId=155 y funciona, lo unico que ocurre es que dicho ciudadano no posee peticiones y la tabla no aparece.

**Comment by ruano23** [comment]
Reabro esta issue porque logeado como agente bancario no puedo verlas
